### ISSUE TITLE
Arbitrary instance for `NoContent`

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant-mock#2]

**Comment by phadej** [comment]
there is 

``` hs
instance Arbitrary NoContent where
  arbitrary = pure NoContent
```

in https://github.com/haskell-servant/servant-mock/blob/114ed88c014d693990c8e565372dd94f25ed3956/src/Servant/Mock.hs#L189

_EDIT_ it exists at least in servant-mock-0.8.1
